import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import GlobalStyle from "../styles/globalStyle";

const roboto = Roboto(
  { weight : '400', 
    subsets : ['latin'], 
  });

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={roboto.className}>{children}</body>
      <GlobalStyle/>
    </html>
  );
}
