
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import GlobalStyle from "../styles/globalStyle";
import ThemeProviderNext from "../themeProvider/themeProvider";
import { Header } from "../components/header";


const roboto = Roboto(
  { weight : '400', 
    subsets : ['latin'], 
  });

export const metadata: Metadata = {
  title: "Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="pt-br">
      <ThemeProviderNext>
        <body className={roboto.className}>
          <Header />
          {children}
        
        </body>
        <GlobalStyle/>
      </ThemeProviderNext>
    </html>
    
  );
}
